<?php
echo "<section id=\"features\">\n";
echo "      <div class=\"container\">\n";
echo "\n";
echo "        <div class=\"row feature-item\">\n";
echo "          <div class=\"col-lg-6 wow fadeInUp\">\n";
echo "            <img src=\"img/features-1.svg\" class=\"img-fluid\" alt=\"\">\n";
echo "          </div>\n";
echo "          <div class=\"col-lg-6 wow fadeInUp pt-5 pt-lg-0\">\n";
echo "            <h4>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h4>\n";
echo "            <p>\n";
echo "              Ipsum in aspernatur ut possimus sint. Quia omnis est occaecati possimus ea. Quas molestiae perspiciatis occaecati qui rerum. Deleniti quod porro sed quisquam saepe. Numquam mollitia recusandae non ad at et a.\n";
echo "            </p>\n";
echo "            <p>\n";
echo "              Ad vitae recusandae odit possimus. Quaerat cum ipsum corrupti. Odit qui asperiores ea corporis deserunt veritatis quidem expedita perferendis. Qui rerum eligendi ex doloribus quia sit. Porro rerum eum eum.\n";
echo "            </p>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "\n";
echo "        <div class=\"row feature-item mt-5 pt-5\">\n";
echo "          <div class=\"col-lg-6 wow fadeInUp order-1 order-lg-2\">\n";
echo "            <img src=\"img/features-2.svg\" class=\"img-fluid\" alt=\"\">\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-6 wow fadeInUp pt-4 pt-lg-0 order-2 order-lg-1\">\n";
echo "            <h4>Neque saepe temporibus repellat ea ipsum et. Id vel et quia tempora facere reprehenderit.</h4>\n";
echo "            <p>\n";
echo "             Delectus alias ut incidunt delectus nam placeat in consequatur. Sed cupiditate quia ea quis. Voluptas nemo qui aut distinctio. Cumque fugit earum est quam officiis numquam. Ducimus corporis autem at blanditiis beatae incidunt sunt. \n";
echo "            </p>\n";
echo "            <p>\n";
echo "              Voluptas saepe natus quidem blanditiis. Non sunt impedit voluptas mollitia beatae. Qui esse molestias. Laudantium libero nisi vitae debitis. Dolorem cupiditate est perferendis iusto.\n";
echo "            </p>\n";
echo "            <p>\n";
echo "              Eum quia in. Magni quas ipsum a. Quis ex voluptatem inventore sint quia modi. Numquam est aut fuga mollitia exercitationem nam accusantium provident quia.\n";
echo "            </p>\n";
echo "          </div>\n";
echo "          \n";
echo "        </div>\n";
echo "\n";
echo "      </div>\n";
echo "    </section>";
?>