<?php
echo "<section id=\"portfolio\" class=\"section-bg\">\n";
echo "      <div class=\"container\">\n";
echo "\n";
echo "        <header class=\"section-header\">\n";
echo "          <h3 class=\"section-title\">Our Portfolio</h3>\n";
echo "        </header>\n";
echo "\n";
echo "        <div class=\"row\">\n";
echo "          <div class=\"col-lg-12\">\n";
echo "            <ul id=\"portfolio-flters\">\n";
echo "              <li data-filter=\"*\" class=\"filter-active\">All</li>\n";
echo "              <li data-filter=\".filter-app\">App</li>\n";
echo "              <li data-filter=\".filter-card\">Card</li>\n";
echo "              <li data-filter=\".filter-web\">Web</li>\n";
echo "            </ul>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "\n";
echo "        <div class=\"row portfolio-container\">\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/app1.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">App 1</a></h4>\n";
echo "                <p>App</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/app1.jpg\" data-lightbox=\"portfolio\" data-title=\"App 1\" class=\"link-preview\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-web\" data-wow-delay=\"0.1s\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/web3.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">Web 3</a></h4>\n";
echo "                <p>Web</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/web3.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"Web 3\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\" data-wow-delay=\"0.2s\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/app2.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">App 2</a></h4>\n";
echo "                <p>App</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/app2.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"App 2\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-card\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/card2.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">Card 2</a></h4>\n";
echo "                <p>Card</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/card2.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"Card 2\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-web\" data-wow-delay=\"0.1s\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/web2.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">Web 2</a></h4>\n";
echo "                <p>Web</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/web2.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"Web 2\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\" data-wow-delay=\"0.2s\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/app3.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">App 3</a></h4>\n";
echo "                <p>App</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/app3.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"App 3\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-card\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/card1.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">Card 1</a></h4>\n";
echo "                <p>Card</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/card1.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"Card 1\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-card\" data-wow-delay=\"0.1s\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/card3.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">Card 3</a></h4>\n";
echo "                <p>Card</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/card3.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"Card 3\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"col-lg-4 col-md-6 portfolio-item filter-web\" data-wow-delay=\"0.2s\">\n";
echo "            <div class=\"portfolio-wrap\">\n";
echo "              <img src=\"img/portfolio/web1.jpg\" class=\"img-fluid\" alt=\"\">\n";
echo "              <div class=\"portfolio-info\">\n";
echo "                <h4><a href=\"#\">Web 1</a></h4>\n";
echo "                <p>Web</p>\n";
echo "                <div>\n";
echo "                  <a href=\"img/portfolio/web1.jpg\" class=\"link-preview\" data-lightbox=\"portfolio\" data-title=\"Web 1\" title=\"Preview\"><i class=\"ion ion-eye\"></i></a>\n";
echo "                  <a href=\"#\" class=\"link-details\" title=\"More Details\"><i class=\"ion ion-android-open\"></i></a>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "        </div>\n";
echo "\n";
echo "      </div>\n";
echo "    </section>";
?>