<?php
echo "    <section id=\"pricing\" class=\"wow fadeInUp section-bg\">\n";
echo "\n";
echo "      <div class=\"container\">\n";
echo "\n";
echo "        <header class=\"section-header\">\n";
echo "          <h3>Pricing</h3>\n";
echo "          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>\n";
echo "        </header>\n";
echo "\n";
echo "        <div class=\"row flex-items-xs-middle flex-items-xs-center\">\n";
echo "      \n";
echo "          <!-- Basic Plan  -->\n";
echo "          <div class=\"col-xs-12 col-lg-4\">\n";
echo "            <div class=\"card\">\n";
echo "              <div class=\"card-header\">\n";
echo "                <h3><span class=\"currency\"></span>Free<span class=\"period\">/month</span></h3>\n";
echo "              </div>\n";
echo "              <div class=\"card-block\">\n";
echo "                <h4 class=\"card-title\"> \n";
echo "                  Basic Plan\n";
echo "                </h4>\n";
echo "                <ul class=\"list-group\">\n";
echo "                  <li class=\"list-group-item\">Odio animi voluptates</li>\n";
echo "                  <li class=\"list-group-item\">Inventore quisquam et</li>\n";
echo "                  <li class=\"list-group-item\">Et perspiciatis suscipit</li>\n";
echo "                  <li class=\"list-group-item\">24/7 Support System</li>\n";
echo "                </ul>\n";
echo "                <a href=\"#\" class=\"btn\">Choose Plan</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "      \n";
echo "          <!-- Regular Plan  -->\n";
echo "          <div class=\"col-xs-12 col-lg-4\">\n";
echo "            <div class=\"card\">\n";
echo "              <div class=\"card-header\">\n";
echo "                <h3><span class=\"currency\">$</span>29<span class=\"period\">/month</span></h3>\n";
echo "              </div>\n";
echo "              <div class=\"card-block\">\n";
echo "                <h4 class=\"card-title\"> \n";
echo "                  Regular Plan\n";
echo "                </h4>\n";
echo "                <ul class=\"list-group\">\n";
echo "                  <li class=\"list-group-item\">Odio animi voluptates</li>\n";
echo "                  <li class=\"list-group-item\">Inventore quisquam et</li>\n";
echo "                  <li class=\"list-group-item\">Et perspiciatis suscipit</li>\n";
echo "                  <li class=\"list-group-item\">24/7 Support System</li>\n";
echo "                </ul>\n";
echo "                <a href=\"#\" class=\"btn\">Choose Plan</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "      \n";
echo "          <!-- Premium Plan  -->\n";
echo "          <div class=\"col-xs-12 col-lg-4\">\n";
echo "            <div class=\"card\">\n";
echo "              <div class=\"card-header\">\n";
echo "                <h3><span class=\"currency\">$</span>39<span class=\"period\">/month</span></h3>\n";
echo "              </div>\n";
echo "              <div class=\"card-block\">\n";
echo "                <h4 class=\"card-title\"> \n";
echo "                  Premium Plan\n";
echo "                </h4>\n";
echo "                <ul class=\"list-group\">\n";
echo "                  <li class=\"list-group-item\">Odio animi voluptates</li>\n";
echo "                  <li class=\"list-group-item\">Inventore quisquam et</li>\n";
echo "                  <li class=\"list-group-item\">Et perspiciatis suscipit</li>\n";
echo "                  <li class=\"list-group-item\">24/7 Support System</li>\n";
echo "                </ul>\n";
echo "                <a href=\"#\" class=\"btn\">Choose Plan</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "      \n";
echo "        </div>\n";
echo "      </div>\n";
echo "\n";
echo "    </section>";

?>